name = "axelink-lp"
compatibility_date = "2024-01-01"

# @cloudflare/next-on-pagesに必要な互換性フラグ
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages/Workers用の設定
pages_build_output_dir = ".vercel/output/static"

